# Copyright (c) 2015-16 Anirvan BASU, INRIA Rennes - Bretagne Atlantique
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. 

config:
site: sophia          # Grid 5000 site for deploying Ceph cluster
g5kCluster: suno      # Grid 5000 cluster in specified site
release: firefly      # Ceph Release name
env: "wheezy-x64-nfs" # G5K environment to be deployed
jobName: cephDeploy   # Name of Grid'5000 job if already created
cephCluster: ceph     # Ceph cluster name
numNodes: 6           # Nodes in Ceph cluster
walltime: "01:00:00"  # Wall time for Ceph cluster deployed
multiOSD: false       # ultiple OSDs on each node
poolName: pool        # Name of pool to create on Ceph clusters
poolSize: 57600       # Size of pool to create on Ceph clusters
rbdName: image        # Name of rbd to create inside Ceph pool
rbdSize: 57600        # Size of rbd to create inside Ceph pool
fileSystem: ext4      # File System to be formatted on created RBD
mntDepl: "ceph-depl"  # Mount point for RBD on deployed cluster
mntProd: "ceph-prod"  # Mount point for RBD on production cluster

